typography_spectrum: 0.08311675
color:
  saturation: 0.949324
  brandStrength: 0.7118998
  lightness: 0.4211583
  rhythmicContrast: 0.932497
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f850d11c-2f37-438a-a92f-42cdfdce5ee6.jpg
name: SwingoutLive!
title: The Big Swing.
description: Music. Dances. Fashions. Films. Food.
